name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # или другая ветка, из которой деплоить

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          npm install

      - name: Build project
        run: |
          npm run build

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages  # Ветка для GitHub Pages
          folder: dist  # Папка с билдом (React по умолчанию билдит в build/)
